version: "3.9"
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0.25
    # M1の時つける
    # platform: linux/amd64
    environment:
      MYSQL_DATABASE: rails-db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_HOST: "%"
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3308
